"""
It is a test file for developing the Anderson-Holstein model (Newns-Anderson Hamiltonian).
"""


using Test
using NQCModels
using LinearAlgebra
""" The tests generated by James Gardner 
m = ErpenbeckThoss(;Γ=0.1)
b = TrapezoidalRule(10, -10, 10)
@testset "nelectrons" begin
    model = AndersonHolstein(m, b) # fermilevel defaults to zero
    @test NQCModels.nelectrons(model) == 5

    for (n, f) in zip([1, 6, 10], [-10, 2, 10])
        model = AndersonHolstein(m, b; fermi_level=f)
        @test NQCModels.nelectrons(model) == n
    end
end
"""
## Test by Hokseon

m = ErpenbeckThoss(;Γ=0.1)
b = TrapezoidalRule(10, -10, 10)

model = AndersonHolstein(m, b) # fermilevel defaults to zero

NQCModels.potential!(model, Hermitian(zeros(11,11)), zeros(1,1))
