[deps]
prettytable = ""
matplotlib = ""
ase = ""
opt_einsum = ""
pandas = ""
e3nn = ""
numpy = "<2.0"
scipy = ""

[deps.torchaudio]
channel = "pytorch"

[deps.torchvision]
channel = "pytorch"

[deps.pytorch]
channel = "pytorch"

[pip.deps]
mace-torch = "@git+https://github.com/ACEsuit/mace.git@v0.3.3"
