name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest

      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: libxc-4.3.4
        with:
          path: $HOME/libxc-4.3.4
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Install Libxc
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget http://www.tddft.org/programs/libxc/down.php?file=4.3.4/libxc-4.3.4.tar.gz -O libxc-4.3.4.tar.gz
          tar -xf libxc-4.3.4.tar.gz
          cd libxc-4.3.4
          ./configure --enable-shared --disable-fortran --prefix=$HOME/libxc-4.3.4
          make
          make install
          cd ..

      - name: Install ase
        run: |
          python3 -m pip install ase 

      - name: Install GPAW
        run: |
          mkdir $HOME/.gpaw
          touch $HOME/.gpaw/siteconfig.py
          echo "library_dirs += ['$HOME/libxc-4.3.4/lib']" >> $HOME/.gpaw/siteconfig.py
          echo "include_dirs += ['$HOME/libxc-4.3.4/include']" >> $HOME/.gpaw/siteconfig.py
          python3 -m pip install gpaw

      - name: Add NQCDRegistry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/NQCD/NQCDRegistry"))'
      - name: Add JuliaMolSim registry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaMolSim/MolSim"))'

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          LD_LIBRARY_PATH: $HOME/libxc-4.3.4/lib
          PYTHONPATH: $HOME/libxc-4.3.4/lib:$PYTHONPATH
          PATH: $HOME/libxc-4.3.4/lib:$PATH

