name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest

      - name: Install Libxc
        run: |
          wget http://www.tddft.org/programs/libxc/down.php?file=4.3.4/libxc-4.3.4.tar.gz -O libxc-4.3.4.tar.gz
          tar -xf libxc-4.3.4.tar.gz
          cd libxc-4.3.4
          ./configure --enable-shared --disable-fortran --prefix=$HOME/libxc-4.3.4
          make
          make install

      - name: Install ase
        run: |
          python3 -m pip install ase 

      - name: Install GPAW
        run: |
          mkdir $HOME/.gpaw
          touch $HOME/.gpaw/siteconfig.py
          echo "library_dirs += ['$HOME/libxc-4.3.4/lib']" >> $HOME/.gpaw/siteconfig.py
          echo "include_dirs += ['$HOME/libxc-4.3.4/include']" >> $HOME/.gpaw/siteconfig.py
          python3 -m pip install gpaw
          export LD_LIBRARY_PATH = $HOME/libxc-4.3.4/lib:$LD_LIBRARY_PATH

      - name: Add NQCDRegistry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/NQCD/NQCDRegistry"))'
      - name: Add JuliaMolSim registry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaMolSim/MolSim"))'

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
