name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest

      - name: Install Libxc
        run: |
          wget http://www.tddft.org/programs/libxc/down.php?file=5.1.5/libxc-5.1.5.tar.gz -O libxc-5.1.5.tar.gz
          tar -xf libxc-5.1.5.tar.gz
          cd libxc-5.1.5
          ./configure --enable-shared --disable-fortran --prefix=$HOME/libxc-5.1.5
          make
          make install
          ln -s $HOME/libxc-5.1.5/lib /usr/lib

      - name: Install ase
        run: |
          python3 -m pip install ase 

      - name: Install GPAW
        run: |
          mkdir $HOME/.gpaw
          touch $HOME/.gpaw/siteconfig.py
          echo "library_dirs += ['$HOME/libxc-5.1.5/lib']" >> $HOME/.gpaw/siteconfig.py
          echo "include_dirs += ['$HOME/libxc-5.1.5/include']" >> $HOME/.gpaw/siteconfig.py
          python3 -m pip install gpaw
          cd /
          ls

      - name: Add NQCDRegistry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/NQCD/NQCDRegistry"))'
      - name: Add JuliaMolSim registry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaMolSim/MolSim"))'

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
