name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest

      - name: Install Libxc
        run: |
          wget http://www.tddft.org/programs/libxc/down.php?file=4.3.4/libxc-4.3.4.tar.gz -O libxc-4.3.4.tar.gz
          tar -xf libxc-4.3.4.tar.gz
          cd libxc-4.3.4
          ./configure --prefix=$HOME/libxc-4.3.4
          make
          make install

      - name: Install ase
        run: |
          python3 -m pip install ase 

      - name: Install GPAW
        run: |
          git clone -b 21.6.0 https://gitlab.com/gpaw/gpaw.git
          cd gpaw
          touch siteconfig.py
          echo "library_dirs += ['~/libxc-4.3.4/lib']" >> siteconfig.py
          echo "include_dirs += ['~/libxc-4.3.4/include']" >> siteconfig.py
          python3 setup.py build
          python3 setup.py install

      - name: Add NQCDRegistry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/NQCD/NQCDRegistry"))'
      - name: Add JuliaMolSim registry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaMolSim/MolSim"))'

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
